http:
  base_url: http://mabinogi.nexon.co.jp
  trade_url: /community/tradeBoardList.asp?sv=
  #Target Severs[ma|ru|ta]
  target_server: ta

db:
  host: localhost:27017
  database: kipit-crawler

twitter:
  screen_name: mecha_pentagon
  consumer_key: TWITTER_CONSUMER_KEY
  consumer_secret: TWITTER_CONSUMER_SECRET
  access_token: TWITTER_ACCESS_TOKEN
  access_token_secret: TWITTER_ACCESS_TOKEN_SECRET

  texts:
    refollow_text: |-
      はじめましてっ！
      ムーニャと言います(๑•̀ㅂ•́)و✧
      + [キーワード]で検索ワードを登録してね(•ө•)♡
